# 介绍

当程序的某部分检测到一个它无法处理的问题时，需要用到异常处理。此时，检测出问题的部分应该发出某种信号以表明程序遇到了故障，无法继续下去了，而且.信号的发出方无须知道故障将在何处得到解决. 一旦发出异常信号，检测出问题的部分也就完成了任务.

异常处理机制为程序中异常检测和异常处理这两部分的协作提供支持。在C++语言中，异常处理包括:

* **throw表达式(throw expression)**，异常检测部分使用throw表达式来表示它遇到了无法处理的问题。我们说 throw引发（raise）了异常.
* **try语句块(try block)**，异常处理部分使用try语句块处理异常。try语句块以关键字try开始，并以一个或多个catch子句(catch clause）结束。try语句块中代码抛出的异常通常会被某个catch子句处理。因为catch子句“处理”异常，所以它们也被称作异常处理代码（exception handler).
* **一套异常类(exception class)**，用于在throw表达式和相关的catch子句之间传递异常的具体信息.

# throw表达式

程序的异常检测部分使用throw表达式引发一个异常。throw表达式包含关键字throw和紧随其后的一个表达式，其中表达式的类型就是抛出的异常类型。throw表达式后面通常紧跟一个分号，从而构成一条表达式语句.

```cpp
if (item1.isbn() != item2.isbn()) {
    throw runtime_error("Data must be refer to name ISBN");
}
```

在这段代码中，如果ISBN 不一样就抛出一个异常，该异常是类型`runtime_error`的对象。抛出异常将终止当前的函数，并把控制权转移给能处理该异常的代码.

类型`runtime_error`是标准库异常类型的一种，定义在`stdexcept`头文件中. 我们必须初始化`runtime_error`的对象，方式是给它提供一个`string`对象或者一个C风格的字符串，这个字符串中有一些关于异常的辅助信息. 

# try语句块

try 语句块的通用语法形式是

```cpp
try {
    program-statement
} catch (exception-declaration) {
    handler-statement
} catch (exception-declaration) {
    handler-statement
} // ...
```

try语句块的一开始是关键字try，随后紧跟着一个块，这个块就像大多数时候那样是花括号括起来的语句序列。

跟在try 块之后的是一个或多个catch子句。catch子句包括三部分:关键字catch、括号内一个(可能未命名的）对象的声明(称作**异常声明，exception declaration**) 以及一个块。当选中了某个catch子句处理异常之后，执行与之对应的块。catch一旦完成，程序跳转到try语句块最后一个catch子句之后的那条语句继续执行.

try语句块中的program-statements组成程序的正常逻辑，像其他任何块一样，program-statements可以有包括声明在内的任意C++语句。一如往常，try语句块内声明的变量在块外部无法访问，特别是在catch子句内也无法访问.

# 函数在寻找处理代码的过程中退出

在复杂系统中，程序在遇到抛出异常的代码前，其执行路径可能已经经过了多个try语句块。例如，一个try语句块可能调用了包含另一个try语句块的函数，新的try语句块可能调用了包含又一个try语句块的新函数，以此类推。

寻找处理代码的过程与函数调用链刚好相反。当异常被抛出时，首先搜索抛出该异常的函数。如果没找到匹配的 catch子句，终止该函数，并在调用该函数的函数中继续寻找。如果还是没有找到匹配的 catch子句，这个新的函数也被终止，继续搜索调用它的函数。以此类推，沿着程序的执行路径逐层回退，直到找到适当类型的catch子句为止。

如果最终还是没能找到任何匹配的 catch子句，程序转到名为`terminate`的标准库函数。该函数的行为与系统有关，一般情况下，执行该函数将导致程序非正常退出。

对于那些没有任何try语句块定义的异常，也按照类似的方式处理:毕竟，没有try语句块也就意味着没有匹配的catch子句。如果一段程序没有try语句块且发生了异常，系统会调用terminate函数并终止当前程序的执行。

# 进阶 - 编写异常安全的代码非常困难

> 要好好理解这句话:异常中断了程序的正常流程。**异常发生时,调用者请求的一部分计算可能已经完成了，另一部分则尚未完成**。通常情况下，略过部分程序意味着某些对象处理到一半就臻然而止,从而导致对象处于无效或未完成的状态，或者资源没有正常释放，等等。那些在异常发生期间正确执行了“清理”工作的程序被称作**异常安全 (exception safe)** 的代码。然而经验表明,编写异常安全的代码非常困难，这部分知识也远远)超出了本书的范围。

# 标准异常 - stdexcept

C++标准库定义了一组类，用于报告标准库函数遇到的问题。这些异常类也可以在用户编写的程序中使用，它们分别定义在4个头文件中:

* `exception`头文件定义了最通用的异常类`exception`。它只报告异常的发生，不提供任何额外信息。
* `stdexcept`头文件定义了几种常用的异常类。

<img src="D:\dev\AllNote\.mdnote\assets\image-20211010132007076.png" alt="image-20211010132007076" style="zoom:80%;" />

